// // @file CodeWriter.cs
// //
// // @copyright Copyright (c) 2026 Retro & Chill. All rights reserved.
// // Licensed under the MIT License. See LICENSE file in the project root for full license information.

using System.Text;
using RetroEngine.Portable.SourceGenerator.Unions.Extensions;

namespace RetroEngine.Portable.SourceGenerator.Unions;

public sealed class CodeWriter : IDisposable
{
#pragma warning disable RS1035
    private static readonly string NewLine = Environment.NewLine;
#pragma warning restore RS1035

    private readonly char? _writeOnClose;
    private readonly StringBuilder _stringBuilder;
    private readonly int _depth;
    private readonly string _depthStr;

    public CodeWriter AppendLine() => AppendLineWithoutTab(string.Empty);

    public CodeWriter()
        : this(new StringBuilder(), 0, null) { }

    public CodeWriter AppendLine(string line) => Append(_depthStr, line, true);

    public CodeWriter Append(string line) => Append(_depthStr, line, false);

    public CodeWriter Append<T>(T value) => Append(value!.ToString());

    public CodeWriter AppendLineWithoutTab(string line) => Append(string.Empty, line, true);

    public CodeWriter NewBlock(char? writeOnClose = null)
    {
        AppendLine("{");
        return new CodeWriter(_stringBuilder, _depth + 1, writeOnClose);
    }

    public void Dispose()
    {
        if (_depth > 0)
        {
            Append(new string('\t', _depth - 1), $"}}{_writeOnClose}", true);
        }
    }

    public override string ToString() => _stringBuilder.ToString();

    public static CodeWriter CreateWithDefaultLines() =>
        new CodeWriter()
            .AppendLine("// <auto-generated> This file has been auto generated. </auto-generated>")
            .AppendLine("#nullable enable");

    private CodeWriter(StringBuilder stringBuilder, int depth, char? writeOnClose)
    {
        _stringBuilder = stringBuilder;
        _depth = depth;
        _depthStr = new string('\t', depth);
        _writeOnClose = writeOnClose;
    }

    private CodeWriter Append(string depthStr, string line, bool newLine)
    {
        if (
            _stringBuilder.Length > 0
            && line != "}"
            && _stringBuilder[^(NewLine.Length + 1)] == '}'
            && _stringBuilder[^(NewLine.Length + 2)] is '\n' or '\t'
        )
        {
            _stringBuilder.AppendLine();
        }

        if (_stringBuilder.EndsWith(NewLine) && depthStr.Length > 0)
        {
            _stringBuilder.Append(depthStr);
        }

        _stringBuilder.Append(line);
        if (newLine)
        {
            _stringBuilder.AppendLine();
        }

        return this;
    }
}
