// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetroEngine.Editor.Core.Data;

#nullable disable

namespace RetroEngine.Editor.Core.Data.Migrations
{
    [DbContext(typeof(CachedDbContext))]
    [Migration("20260314152508_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("RetroEngine.Editor.Core.Data.Entities.RecentProject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("LastOpened")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_opened");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.HasKey("Id")
                        .HasName("pk_recent_projects");

                    b.HasIndex("LastOpened")
                        .HasDatabaseName("ix_recent_projects_last_opened");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasDatabaseName("ix_recent_projects_path");

                    b.ToTable("recent_projects", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
