import json
from io import TextIOWrapper

SKIP_FILES = ['SDL3pp_main.h', 'SDL3pp_vulkan.h']


def walk_entries(parent: dict, current_namespace: str = "SDL", intent_level: int = 1, file: TextIOWrapper | None = None):
    for _, entry in parent['entries'].items():
        if entry['kind'] == 'def' or entry['kind'] == 'forward' or (entry['kind'] == 'function' and '::' in entry['name']):
            continue

        if entry['kind'] == 'ns':
            print('    ' * intent_level +
                  f'namespace {entry["name"]} {{', file=file)
            walk_entries(entry, entry['name'], intent_level + 1, file=file)
            print('    ' * intent_level + '}', file=file)

            print('    ' * intent_level + 'using ' +
                  current_namespace + '::' + entry['name'] + ';', file=file)


def main():
    with open('target.json', 'r') as f:
        target = json.load(f)

    with open('output.ixx', 'w') as f:
        print('// This file is automatically generated by sdl3pp-module-builder', file=f)
        print('module;', file=f)
        print('', file=f)
        print('#include <SDL3pp/SDL3pp.h>', file=f)
        print('', file=f)
        print('export module sdl;', file=f)
        print('', file=f)
        print('export namespace SDL {', file=f)
        for _, file in target['files'].items():
            if file['name'] in SKIP_FILES:
                continue
            print(f'    // {file["name"]}', file=f)
            walk_entries(file, file=f)
            print(file=f)

        print('}', file=f)


if __name__ == "__main__":
    main()
