//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroEngine.SourceGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SourceTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SourceTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RetroEngine.SourceGenerator.Properties.SourceTemplates", typeof(SourceTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using RetroEngine.Binds;
        ///
        ///namespace {{ManagedNamespace}};
        ///
        ///unsafe class {{Name}}
        ///{
        ///    {{#Methods}}
        ///    private static readonly delegate *unmanaged&lt;{{#Parameters}}{{ManagedType}}, {{/Parameters}}{{ManagedReturnType}}&gt; {{Name}}_Delegate;
        ///    {{/Methods}}
        ///
        ///    static {{Name}}()
        ///    {
        ///        {{#Methods}}
        ///        var {{Name}}_Delegate_Size = {{DelegateSize}}
        ///        LookupDelegate = (delegate *unmanaged&lt;{{#Parameters}}{{ManagedType}}, {{/Parameters}}{{ManagedReturnType}}&gt;) BindsManager.GetBoundFu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BindsExporterTemplate {
            get {
                return ResourceManager.GetString("BindsExporterTemplate", resourceCulture);
            }
        }
    }
}
