name: Build Native

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg_cache,readwrite

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: '~4.1.0'

      - name: Install Linux Build Dependencies
        if: runner.os == 'Linux'
        run: sudo apt install autoconf autoconf-archive automake libtool libltdl-dev

      - name: Setup UV
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b

      - name: Install Python Dependencies
        run: uv sync --all-packages

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/vcpkg_cache
          key: vcpkg-${{ matrix.os }}-${{ hashFiles('vcpkg.json', 'vcpkg_overlay/**') }}

      - name: Setup VCPKG
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg_cache'
          vcpkgGitCommitId: '89dd0f4d241136b843fb55813b2f0fa6448c204d'
          vcpkgJsonGlob: '${{ github.workspace }}/vcpkg.json'

      - name: Run CMake with vcpkg.json manifest
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: release
