name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg_cache,readwrite

jobs:
  build-native:
    name: Build Native (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: '~4.1.0'

      - name: Install Linux Build Dependencies
        if: runner.os == 'Linux'
        run: sudo apt install autoconf autoconf-archive automake libtool libltdl-dev

      - name: Setup UV
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b

      - name: Install Python Dependencies
        run: uv sync --all-packages

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/vcpkg_cache
          key: vcpkg-${{ matrix.os }}-${{ hashFiles('vcpkg.json', 'vcpkg_overlay/**') }}

      - name: Setup VCPKG
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg_cache'
          vcpkgGitCommitId: '89dd0f4d241136b843fb55813b2f0fa6448c204d'
          vcpkgJsonGlob: '${{ github.workspace }}/vcpkg.json'

      - name: Run CMake with vcpkg.json manifest
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: native-build-${{ matrix.os }}
          path: ${{ github.workspace }}/engine/build/release/runtimes/**/*
          retention-days: 5

  build-managed:
    name: Build Managed
    runs-on: windows-latest
    needs: build-native

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: native-build-windows-latest
          path: ${{ github.workspace }}/engine/build/release/runtimes/

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Restore
        run: dotnet restore RetroEngine.Managed.slnx

      - name: Build
        run: dotnet build RetroEngine.Managed.slnx --configuration Release --no-restore
